/*
 * This file is generated by jOOQ.
*/
package com.makhnov.springbootcalculator.jooq;


import com.makhnov.springbootcalculator.jooq.tables.PostfixResults;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>postfix_results</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index POSTFIX_RESULTS_PRIMARY = Indexes0.POSTFIX_RESULTS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index POSTFIX_RESULTS_PRIMARY = Internal.createIndex("PRIMARY", PostfixResults.POSTFIX_RESULTS_, new OrderField[] { PostfixResults.POSTFIX_RESULTS_.ID }, true);
    }
}
