/*
 * This file is generated by jOOQ.
*/
package com.makhnov.springbootcalculator.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostfixResults extends SchemaImpl {

    private static final long serialVersionUID = 1128465445;

    /**
     * The reference instance of <code>postfix_results</code>
     */
    public static final PostfixResults POSTFIX_RESULTS = new PostfixResults();

    /**
     * The table <code>postfix_results.postfix_results</code>.
     */
    public final com.makhnov.springbootcalculator.jooq.tables.PostfixResults POSTFIX_RESULTS_ = com.makhnov.springbootcalculator.jooq.tables.PostfixResults.POSTFIX_RESULTS_;

    /**
     * No further instances allowed
     */
    private PostfixResults() {
        super("postfix_results", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.makhnov.springbootcalculator.jooq.tables.PostfixResults.POSTFIX_RESULTS_);
    }
}
