/*
 * This file is generated by jOOQ.
*/
package com.makhnov.springbootcalculator.jooq;


import com.makhnov.springbootcalculator.jooq.tables.PostfixResults;
import com.makhnov.springbootcalculator.jooq.tables.UsersExpressions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in postfix_results
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>postfix_results.postfix_results</code>.
     */
    public static final PostfixResults POSTFIX_RESULTS_ = com.makhnov.springbootcalculator.jooq.tables.PostfixResults.POSTFIX_RESULTS_;

    /**
     * The table <code>postfix_results.users_expressions</code>.
     */
    public static final UsersExpressions USERS_EXPRESSIONS = com.makhnov.springbootcalculator.jooq.tables.UsersExpressions.USERS_EXPRESSIONS;
}
